### ISSUE TITLE
Make masters unschedulable

### ISSUE THREAD

**Issue by jfblaine** [noseka1/openshift-auto-upi#10]
Is there way to not make the masters schedulable?

**Comment by jfblaine** [comment]
For clarity's sake, what I mean is when the cluster is up, the masters are listed as having both the master and worker role (ROLE: master,worker).  Is there a way to set the configuration so the masters only have the master role?

**Comment by jfblaine** [comment]
Talked to Ales about this, he explained he generally makes this change after the install completes.  I will do the same, if we feel there is some super compelling reason to do it prior to the install, he explained he may add the feature at that point.

**Comment by noseka1** [comment]
This can now be achieved by leveraging the filetranspiler feature that will be part of the 1.6 release:
https://github.com/noseka1/openshift-auto-upi/blob/master/docs/customizing_ignition_configs.md

The filetranspiler samples include the example of setting the masters to be unschedulable:
https://github.com/noseka1/openshift-auto-upi/blob/master/docs/examples/ignition/filetranspiler/bootstrap/opt/openshift/manifests/cluster-scheduler-02-config.yml
