### ISSUE TITLE
expired ignition files

### ISSUE THREAD

**Issue by jfblaine** [noseka1/openshift-auto-upi#15]
I deleted/recreated a cluster over the course of more than 24h and found after 24h I received the x509 error.  What I did to trigger the code to recreate the ign files was to delete the following file:

rm -rf /root/openshift-auto-upi-workspace/autoupi/timestamps/ignition_created

If this is the correct course of action, may be worth calling out in the readme

**Comment by jfblaine** [comment]
I actually found to clear the x509 error I needed to run the following:

rm -rf /root/openshift-auto-upi-workspace/autoupi/timestamps /root/openshift-auto-upi-workspace/autoupi/conf

**Comment by noseka1** [comment]
Thanks for reporting this. Yes, that's exactly the right course of action. I added an item to the backlog to document this.
