### ISSUE TITLE
Ovirt installation failed (OCP 4.6.42) - Please use openshift-auto-upi version <= 1.8 for installing OpenShift < 4.8

### ISSUE THREAD

**Issue by arunabhabanerjee** [noseka1/openshift-auto-upi#35]
Could you please help?

`TASK [openshift_common : Fetch CoreOS stream metadata] ***************************************************************************************************************************************************************************************
task path: /root/openshift-auto-upi/roles/openshift_common/tasks/read_coreos_stream.yml:1
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
File lookup using /root/.ssh/id_rsa.pub as file
<helper> ESTABLISH LOCAL CONNECTION FOR USER: root
<helper> EXEC /bin/sh -c 'echo ~root && sleep 0'
<helper> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058 `" && echo ansible-tmp-1629112332.8977733-13353-151270198623058="` echo /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/commands/command.py
<helper> PUT /root/.ansible/tmp/ansible-local-12955724kecwb/tmp5vr99ehu TO /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058/AnsiballZ_command.py
<helper> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058/ /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058/AnsiballZ_command.py && sleep 0'
<helper> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058/AnsiballZ_command.py && sleep 0'
<helper> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1629112332.8977733-13353-151270198623058/ > /dev/null 2>&1 && sleep 0'
fatal: [helper]: FAILED! => {
    "changed": false,
    "cmd": [
        "/root/openshift-auto-upi-workspace/optage/bin/openshift-install",
        "coreos",
        "print-stream-json"
    ],
    "delta": "0:00:00.051074",
    "end": "2021-08-16 07:12:13.072031",
    "invocation": {
        "module_args": {
            "_raw_params": "/root/openshift-auto-upi-workspace/optage/bin/openshift-install coreos print-stream-json",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-08-16 07:12:13.020957",
    "stderr": "time=\"2021-08-16T07:12:13-04:00\" level=fatal msg=\"Error executing openshift-install: unknown command \\\"coreos\\\" for \\\"openshift-install\\\"\"",
    "stderr_lines": [
        "time=\"2021-08-16T07:12:13-04:00\" level=fatal msg=\"Error executing openshift-install: unknown command \\\"coreos\\\" for \\\"openshift-install\\\"\""
    ],
    "stdout": "",
    "stdout_lines": []
}
...ignoring

TASK [openshift_common : fail] ***************************************************************************************************************************************************************************************************************
task path: /root/openshift-auto-upi/roles/openshift_common/tasks/read_coreos_stream.yml:7
fatal: [helper]: FAILED! => {
    "changed": false,
    "msg": "Please use openshift-auto-upi version <= 1.8 for installing OpenShift < 4.8. This openshift-auto-upi version only supports OpenShift >= 4.8."
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
helper                     : ok=11   changed=1    unreachable=0    failed=1    skipped=6    rescued=0    ignored=1`

**Comment by arunabhabanerjee** [comment]
Please let me know how I can use openshift-auto-upi version <= 1.8 for installing OpenShift 4.6.42.

**Comment by noseka1** [comment]
Hi @arunabhabanerjee , The instructions on how to check out a specific openshift-auto-upi version can be found in the [Setting up Helper Host](https://github.com/noseka1/openshift-auto-upi/#setting-up-helper-host). For example, to use openshift-auto-upi 1.8 you will do:

```
$ git clone https://github.com/noseka1/openshift-auto-upi.git
$ git checkout 1.8
$ cd openshift-auto-upi
```

**Comment by arunabhabanerjee** [comment]
Thank you for the quick response.

Now I am facing issue while downloading RHCOS image. I am using version 1.7.

`TASK [openshift_common : Download CoreOS image from {{ download_coreos_url }}] ***************************************************************************************************************************************************************
task path: /root/openshift-auto-upi/roles/openshift_common/tasks/download_coreos.yml:16
File lookup using /root/.ssh/id_rsa.pub as file
fatal: [helper]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: {{ coreos.openstack_qcow2_url }}: {u'qemu_qcow2_url': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].qemu_qcow2_url }}', u'openstack_qcow2_url': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].openstack_qcow2_url }}', u'installer_kernel_url': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].installer_kernel_url }}', u'metal_bios_url': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].metal_bios_url }}', u'checksum': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].checksum }}', u'vmware_ova_url': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].vmware_ova_url }}', u'installer_initramfs_url': u'{{ coreos_versions[openshift_install_config.distribution][openshift_install_config.coreos_version].installer_initramfs_url }}'}: 'dict object' has no attribute u'4.6.40'\n\nThe error appears to be in '/root/openshift-auto-upi/roles/openshift_common/tasks/download_coreos.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download CoreOS image from {{ download_coreos_url }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
helper                     : ok=18   changed=14   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0`

**Comment by arunabhabanerjee** [comment]
I updated the file according to the image version in inventory/group_vars/all/software/coreos.yml file, but still I am getting error.

`fatal: [helper]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "sha256:https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.40/sha256sum.txt",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/root/openshift-auto-upi-workspace/optage/images/rhcos-4.6.40-x86_64-openstack.x86_64.qcow2.gz",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.40/rhcos-4.6.40-x86_64-openstack.x86_64.qcow2.gz",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Unable to find a checksum for file 'rhcos-4.6.40-x86_64-openstack.x86_64.qcow2.gz' in 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.40/sha256sum.txt'"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
helper                     : ok=12   changed=1    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0`

**Comment by arunabhabanerjee** [comment]
I disabled checksum and now I am getting this error:

`fatal: [helper]: FAILED! => {
    "changed": true,
    "cmd": [
        "gunzip",
        "--keep",
        "/root/openshift-auto-upi-workspace/optage/images/rhcos-4.6.40-x86_64-openstack.x86_64.qcow2.gz"
    ],
    "delta": "0:00:00.004776",
    "end": "2021-08-16 11:58:48.480188",
    "invocation": {
        "module_args": {
            "_raw_params": "gunzip --keep '/root/openshift-auto-upi-workspace/optage/images/rhcos-4.6.40-x86_64-openstack.x86_64.qcow2.gz'",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": "/root/openshift-auto-upi-workspace/optage/images/rhcos-4.6.40-x86_64-openstack.x86_64.qcow2",
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-08-16 11:58:48.475412",
    "stderr": "gzip: unrecognized option '--keep'\nTry `gzip --help' for more information.",
    "stderr_lines": [
        "gzip: unrecognized option '--keep'",
        "Try `gzip --help' for more information."
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
helper                     : ok=14   changed=2    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0`

**Comment by arunabhabanerjee** [comment]
Please ignore, I have deployed the cluster successfully.
